### ISSUE TITLE
Add "requests" dependency to the documentation

### ISSUE THREAD

**Issue by valconius** [ehoneyse/mpv-open-anilist-page#2]
I needed not only "guessit" but also "requests", so can you please add "requests" to the list of dependencies in your README?

The context was installing mpv into NixOS with only those dependencies needed for the script without exposing those dependencies to the user. In this case, that means a nix user puts something like the following in their system configuration (or uses an overlay in their user configuration then "installs" the modified package). Something similar applies for GuixSD.
```
(mpv-with-scripts.overrideAttrs (oldAttrs: {
      scripts = [
        mpvScripts.mpris
      ];
      buildInputs = oldAttrs.buildInputs ++ [
        (python3.withPackages (ps: with ps; [
          # mpv-open-anilist-page needs two packages:
          guessit
          requests
        ]))
      ];
    }))
```

**Comment by ehoneyse** [comment]
Hey, thanks for letting me know! I updated the README to reflect the need for `requests`. I think eventually I would like a proper requirements.txt (I am doing some CI on another branch), so I may change how it looks in the future. Good to know that was needed for certain systems.

Closing the issue for now, feel free to re-open if I misunderstood.
